apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.backend.name }}
  name: {{ .Values.backend.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
      - image: {{ .Values.backend.name }}
        name: {{ .Values.backend.name }}
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: iac-database-config
          - secretRef:
              name: iac-database-secret

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-svc
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: 8000
      targetPort: 8000
