apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: iac-database
  name: iac-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iac-database
  serviceName: "database"
  template:
    metadata:
      labels:
        app: iac-database
    spec:
      containers:
        - image: postgres:13.2-alpine
          name: iac-database
          envFrom:
            - configMapRef:
                name: iac-database-config
            - secretRef:
                name: iac-database-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: iac-database-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: iac-database-svc
spec:
  selector:
    app: iac-database
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: iac-database-config
data:
  POSTGRES_HOST: iac-database-svc
  POSTGRES_DB: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: iac-database-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: iac-database-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iac-database-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
