apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress-frontend
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: iac-frontend-svc
              port:
                number: 3000
        - path: /api(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: iac-backend-svc
              port:
                number: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress-backend-static
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /static/$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /static(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: iac-backend-svc
              port:
                number: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress-frontend-static
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /_next/$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /_next(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: iac-frontend-svc
              port:
                number: 3000
